### ISSUE TITLE
Unable to import packages 

### ISSUE THREAD

**Issue by elenaparaschiv** [googleapis/python-analytics-data#207] opened 2022-03-11 21:20 UTC
I completed the steps in readme. When I try running any of the files I get import errors.
 For example  at  **quickstart.py**  on the import line 1 : 
` from google.analytics.data_v1beta import BetaAnalyticsDataClient
`
returns the following error
 **“AttributeError: module 'google.analytics' has no attribute 'data_v1beta'”**

In terminal I  tried executing :

```
$ python
>>> import google

>>> google.analytics
<module 'google.analytics' (namespace)>

>>> google.analytics.data_v1beta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.analytics' has no attribute 'data_v1beta'
```
![Screenshot 2022-03-11 at 22 19 24](https://user-images.githubusercontent.com/16779941/157968398-0e10acc0-fc8b-4a12-a90c-6d9a7a2b4f18.png)

**Comment by busunkim96** [comment] 2022-03-14 15:27
Hi @elenaparaschiv,

I'm not able to reproduce the issue - the import works as expected for me. Could you try following these steps?

1. Create virtualenv.
```
python3 -m venv env
source env/bin/activate
```

3. Install `google-analytics-data`.
```
pip install google-analytics-data
```

5. Run code.

```
(env) busunkim@busunkim:~/bugs$ python3
Python 3.9.9 (main, Jan 12 2022, 16:10:51) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.analytics.data_v1beta import BetaAnalyticsDataClient
>>> client = BetaAnalyticsDataClient()
```

**Comment by suztomo** [comment] 2023-08-16 20:50
Closing for obsolete and not-reproducible.

**Closed by suztomo** 2023-08-16 20:50 UTC
Labels: type: question, api: analyticsdata
